version: "3"

###################
# PRODUCTION
###################

services:
  app:
    build:
      context: .
      target: prod
    env_file: .env
    container_name: cicd
    restart: unless-stopped
    ports:
      - "3000:3000"

###################
# DEVELOPER
###################

# services:
#   app:
#     build:
#       context: .
#       target: devdeps
#     env_file: .env
#     container_name: cicd
#     command: npm run start:dev
#     restart: unless-stopped
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
