version: "3"

services:
  app:
    build:
      context: .
      target: dev
    env_file: .env
    container_name: api_service
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
